In [2]:
import torch
from torch import nn
from torch.nn import functional as F
from d2l import torch as d2l

In [3]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

In [4]:
layer = CenteredLayer()
layer(torch.tensor([1.0, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [5]:
net = nn.Sequential(nn.LazyLinear(128), CenteredLayer())

C:\Users\elaim\miniconda3\envs\d2l\lib\site-packages\torch\nn\modules\lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


In [6]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(7.4506e-09, grad_fn=<MeanBackward0>)

In [7]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [8]:
linear = MyLinear(5, 3) # 给权重和偏置赋值
linear.weight

Parameter containing:
tensor([[-0.5330, -1.6268,  1.4759],
        [-0.2228, -0.3814, -0.5851],
        [-0.7432,  1.4242, -0.1002],
        [-0.4747, -0.4207,  0.1872],
        [-0.9578, -0.4291,  0.2885]], requires_grad=True)

In [9]:
linear(torch.rand(2, 5)) # 输入参数前向传播得到结果

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.7772]])

In [10]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[1.6436],
        [0.0000]])

In [ ]:
""" Exercise
1.
2.
"""