In [4]:
import torch
from torch import nn

In [5]:
net = nn.Sequential(nn.LazyLinear(8),
                    nn.ReLU(),
                    nn.LazyLinear(1))

X = torch.rand(size=(2, 4))
net(X).shape

torch.Size([2, 1])

In [7]:
net[2].state_dict() # weight 权重，bias 偏差

OrderedDict([('weight',
              tensor([[-0.1559, -0.0523, -0.2598,  0.2269,  0.2362,  0.0735, -0.1249, -0.1937]])),
             ('bias', tensor([0.1177]))])

In [8]:
type(net[2].bias), net[2].bias.data

(torch.nn.parameter.Parameter, tensor([0.1177]))

In [9]:
net[2].weight.grad == None

True

In [12]:
[(name, param.shape) for name, param in net.named_parameters()]

[('0.weight', torch.Size([8, 4])),
 ('0.bias', torch.Size([8])),
 ('2.weight', torch.Size([8, 8])),
 ('2.bias', torch.Size([8])),
 ('6.weight', torch.Size([1, 8])),
 ('6.bias', torch.Size([1]))]

In [16]:
# We need to give the shared layer a name so that we can refer to its
# parameters
shared = nn.LazyLinear(8)
net = nn.Sequential(nn.LazyLinear(8),
                    nn.ReLU(),
                    shared, nn.ReLU(),
                    shared, nn.ReLU(),
                    nn.LazyLinear(1))

print(net(X))
# Check whether the parameters are the same
print(net[2].weight.data[0] == net[4].weight.data[0])
net[2].weight.data[0, 0] = 100
# Make sure that they are actually the same object rather than just having the
# same value
print(net[2].weight.data[0] == net[4].weight.data[0])

tensor([[-0.0835],
        [-0.0807]], grad_fn=<AddmmBackward0>)
tensor([True, True, True, True, True, True, True, True])
tensor([True, True, True, True, True, True, True, True])


Exercise:
3. 节省内存，提升模型一致性，减少过拟合，简化模型设计