In [1]:
import torch
from torch import nn
from torch.nn import functional as F

In [3]:
x = torch.arange(4)
torch.save(x, 'x-file')

In [4]:
x2 = torch.load('x-file')
x2

tensor([0, 1, 2, 3])

In [5]:
y = torch.zeros(4)
torch.save([x, y],'x-files')
x2, y2 = torch.load('x-files')
(x2, y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [6]:
mydict = {'x': x, 'y': y}
torch.save(mydict, 'mydict')
mydict2 = torch.load('mydict')
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

In [7]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.LazyLinear(256)
        self.output = nn.LazyLinear(10)

    def forward(self, x):
        return self.output(F.relu(self.hidden(x)))

net = MLP()
X = torch.randn(size=(2, 20))
Y = net(X)

C:\Users\elaim\miniconda3\envs\d2l\lib\site-packages\torch\nn\modules\lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


In [8]:
torch.save(net.state_dict(), 'mlp.params')

In [9]:
clone = MLP()
clone.load_state_dict(torch.load('mlp.params'))
clone.eval()

MLP(
  (hidden): LazyLinear(in_features=0, out_features=256, bias=True)
  (output): LazyLinear(in_features=0, out_features=10, bias=True)
)

In [10]:
Y_clone = clone(X)
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])

In [ ]:
""" Exercise
1. 保存模型参数的实际好处：
    检查和分析模型：保存模型参数后，可以在训练完成后分析权重和偏置，研究模型的表现。
    断点续训：可以在训练中断时保存当前模型参数，以便从中断处继续训练，节省时间。
    实验再现性：保存模型参数可以确保在不同的时间点或不同的环境中重现同样的实验结果。
    版本控制：可以在模型迭代过程中保存不同阶段的模型参数，以便对比和调优。
2. 在不同架构中重用部分网络：
    方法：可以先定义一个新的网络架构，然后将之前网络的前两层的参数加载到新网络中相应的部分。通过 state_dict 和 load_state_dict 可以实现参数部分加载。
    实现：python
        old_model = PreTrainedModel()  # 旧的预训练模型
        new_model = NewModel()  # 新的模型架构
        new_model.layer1.weight.data = old_model.layer1.weight.data  # 重用第一层的参数
        new_model.layer2.weight.data = old_model.layer2.weight.data  # 重用第二层的参数
    注意事项：需要确保新模型的层的输入输出维度与旧模型相匹配，否则会导致参数维度不兼容的问题。
3. 保存方法：可以使用 torch.save() 将模型的结构代码和参数一起保存，或者保存模型的 state_dict（参数字典）和结构代码的独立文件。
    限制：要确保模型架构兼容性，即在加载模型时需要确保模型代码能够正确解释保存的参数；例如，确保层数和顺序一致，输入输出维度匹配。
"""